cod_lookup:
  key: [
    'pcm',
    'labor',
    'congenital',
    'maternal',
    'convulsions',
    'sepsis',
    'hypoxia',
    'respiratory',
    'prematurity',
    'sids',
    'otherspecific',
    'unspecific',
    'unknown'
  ]
  label: [
    'Placenta, cord, membrane',
    'Labor complications',
    'Congenital malformations, deformities and chromosomal anomalies',
    'Maternal conditions',
    'Convulsions and disorders of cerebral status',
    'Sepsis',
    'Hypoxia and asphyxia',
    'Respiratory and cardiovascular disorders',
    'Disorders related to fetal growth and prematurity',
    'Sudden Infant Death Syndrome',
    'Other specific disorders',
    'Unspecific stillbirth',
    'Unknown'
  ]
  shortlabel: [
    'PCM complications',
    'Labor complications',
    'Congenital malformations',
    'Maternal conditions',
    'Convulsions',
    'Sepsis',
    'Hypoxia and asphyxia',
    'Respiratory and cardiovascular',
    'Fetal growth and prematurity',
    'SIDS',
    'Other specific',
    'Unspecific stillbirth',
    'Unknown'
  ]
  color: [
    '#A41D24', # pcm
    '#D8262F', # labor
    '#F47C0C', # congenital
    '#F3AA9B', # maternal
    '#C94EAC', # convulsions
    '#06713B', # sepsis
    '#63ABD2', # hypoxia
    '#3491C4', # respiratory
    '#2B1555', # prematurity
    '#C0C2DA', # sids
    '#3A3A3E', # otherspecific
    '#5A5A5A', # unspecific
    '#222222'  # unknown
  ]

