cod_lookup:
  key: [
    'pcml_complications',
    'congenital_malformations',
    'maternal_complications',
    'infections_parasites_toxins',
    'prematurity',
    'accidents_and_violence',
    'sids',
    'unspecific_stillbirth',
    'other'
  ]
  label: [
      'Placenta, cord, membrane, labour complications',
      'Congenital malformations, deformities and chromosomal anomalies',
      'Maternal complications',
      'Infections, parasites, and toxins',
      'Prematurity',
      'Accidents and violence',
      'Sudden Infant Death',
      'Unspecific stillbirth',
      'Other'
    ]
  shortlabel: [
      'PCML complications',
      'Congenital malformations',
      'Maternal complications',
      'Infections, parasites & toxins',
      'Prematurity',
      'Accidents & violence',
      'SIDS',
      'Unspecific stillbirth',
      'Other'
    ]
  color: [
    '#A41D24', # pcml
    '#F47C0C', # congenital malformations
    '#F3AA9B', # maternal
    '#06713B', # infection
    '#63ABD2', # prematurity
    '#2B1555', # accidents and violence
    '#C0C2DA', # sids
    '#5A5A5A', # unspecific
    '#3A3A3E'  # other
    ]